# nginx proxy address - http://172.17.0.1:50022

name: code-server
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    privileged: true
    tty: true
    stdin_open: true
    user: root
    group_add:
      - root
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      DEFAULT_THEME: Visual Studio Dark
      DEFAULT_WORKSPACE: /data/workspace
      PROXY_DOMAIN: ${BASE_HOST_NAME:-$HOSTNAME}
      PASSWORD: ${APP_USER_PASS:-changeme_user_password}
      SUDO_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      CONTAINER_NAME: code-server-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:50022:8443'
    volumes:
      - './volumes/config/ssh:/config/.ssh'
      - './volumes/config/gnupg:/config/.gnupg'
      - './volumes/data/workspace:/data/workspace'
      - './volumes/data/code-server:/data'
      - './volumes/config/code-server:/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - code-server
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://code-server-app:8443'
      - 'cloudflare.hostname=code-server.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.code-server-app.entrypoints=http'
      - 'traefik.http.routers.code-server-app-secure.tls=true'
      - 'traefik.http.routers.code-server-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.code-server-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.code-server-app.middlewares=code-server-app-https-redirect'
      - 'traefik.http.routers.code-server-app-secure.entrypoints=https'
      - 'traefik.http.routers.code-server-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.code-server-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.code-server-app-secure.service=code-server-app'
      - 'traefik.http.services.code-server-app.loadbalancer.server.port=8443'

networks:
  code-server:
    name: code-server
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
